[package]
name = "AoC-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[[bin]]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "day05"
path = "src/day05.rs"
